[workspace]
members = []

[package]
name = "rust-bootcamp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3
lto = "fat"
strip = true

[workspace.dependencies]
anyhow = "1"

[dependencies]
anyhow = { workspace = true }
